architectury {
    common(rootProject.enabled_platforms.split(','))
}

dependencies {
    // Depend on Fabric Loader here to use the Fabric @Environment annotations
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Architectury API
    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"

    // GeckoLib API
    modImplementation "software.bernie.geckolib:geckolib-fabric-$rootProject.minecraft_version:$rootProject.geckolib_version"

    // Fzzy Config API
    modImplementation "me.fzzyhmstrs:fzzy_config:${rootProject.fzzy_config_version}"

    // Jade API
    modImplementation "curse.maven:jade-324717:${rootProject.jade_version_fabric}"

    // Patchouli API
    modCompileOnly "vazkii.patchouli:Patchouli:${rootProject.patchouli_version}-FABRIC"

    // Iris API (Optional, Compile-Time)
    modCompileOnly "maven.modrinth:iris:${rootProject.iris_version}-fabric"

    testImplementation "org.junit.jupiter:junit-jupiter:5.11.4"
}

sourceSets.test {
    java.srcDirs = ["src/test_1_20_x/java"]
    resources.srcDirs = ["src/test_1_20_x/resources"]
}

tasks.named("test") {
    useJUnitPlatform()
}
